"""
Django settings for Digslient project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url  # ต้องติดตั้งแพ็กเกจ dj-database-url ผ่าน pip install dj-database-url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# โหลดไฟล์ .env
load_dotenv(dotenv_path=BASE_DIR / '.env')

# อ่านค่าจาก .env
MS_CLIENT_ID     = os.getenv("MS_CLIENT_ID")
MS_CLIENT_SECRET = os.getenv("MS_CLIENT_SECRET")
MS_TENANT_ID     = os.getenv("MS_TENANT_ID")

# ใช้ environment variable สำหรับค่า SECRET_KEY เพื่อความปลอดภัย
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-a@=(z$zq_td^*266n(geedk@+zs3f90#jv&l1*1%$gq6%_va6h'
)

# ปรับ DEBUG ตาม environment variable (ค่าเริ่มต้น True สำหรับการพัฒนา)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# กำหนด ALLOWED_HOSTS จาก environment variable หรือค่าเริ่มต้น
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,code-uued.onrender.com').split(',')
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Paramiter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Digslient.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Paramiter' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Digslient.wsgi.application'

# Database
# ใช้ dj_database_url เพื่อให้สามารถเปลี่ยนแปลงฐานข้อมูลผ่าน environment variable ได้
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'Paramiter' / 'static',    # ชี้ไปยังโฟลเดอร์ static หลัก
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration (สำหรับการพัฒนา)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
         'console': {
             'class': 'logging.StreamHandler',
         },
    },
    'root': {
         'handlers': ['console'],
         'level': 'DEBUG' if DEBUG else 'INFO',
    },
}

# STATIC_ROOT คือ path ที่ collectstatic จะนำไฟล์ static มารวมกัน
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'