# Generated by Django 5.1.7 on 2025-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paramiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('External grid', 'หม้อแปลง'), ('CB', 'เบรกเกอร์'), ('LINE', 'สายส่ง'), ('LOAD', 'โหลด')], max_length=50),
        ),
    ]
