# Generated by Django 5.1.7 on 2025-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paramiter', '0002_alter_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('External grid', 'กริด'), ('CB', 'เบรกเกอร์'), ('Recloser', 'รีโคลสเซอร์'), ('Fuse', 'ฟิวส์'), ('LINE', 'สายส่ง'), ('LOAD', 'โหลด')], max_length=50),
        ),
    ]
